[theme]
# Primary accent color for interactive elements.
primaryColor = "#FF6F61"

# Background color for the main content area.
backgroundColor = "#1E1E2F"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#2C2C3E"

# Color used for almost all text.
textColor = "#ECECEC"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
